# A Function in Context

Now that we've seen a few simple functions, let's expand a litte. In this lesson we won't learn much in the way of new material; we'll mostly be examining how we use functions to improve things we already know. 

In a recent problem, we applied a tax to the total cost of a hot sauce spending spree. This is a good example of where a function can make things better: what if we want to apply a different tax rate? We can simply pass the cost and the tax rate to a function instead of changing the math at every point in the code. 

In [6]:

def tax(total, rate):        # define tax, taking total and rate
    rate = 1 + rate          # we add the rate to 1 for easy multiplying
    result = total * rate    # the result is the price times the 1+rate
    return result            # return the results 

test_total = 1.00            # try it on a dollar to check it easily
test_rate = 0.06             # we'll use a 6% rate for whatever reason

print(tax(test_total, test_rate))    # print out the results

1.06


If we wanted to see different results for different rates, we could easily store them in sensibly names variables:

In [9]:

# whatever we want for cost
cost = 200

# try different values and store them
six_pct = tax(cost, 0.06)
five_pct = tax(cost, 0.05)
four_pct = tax(cost, 0.04)

print(six_pct, five_pct, four_pct)

212.0 210.0 208.0


To further illustrate the contextual usage of functions, let's see how we could incorporate this into a useful program. Let's say we need to be sure we spend less than 100 dollars after tax. 

In [16]:

# a list of prices of different hypothetical objects
objects = [95.00, 96.49, 90.02, 89.99]

# our current tax rate is 7%
tax_rate = 0.07

# iterate through
for item in objects:
    # see if it is < 100 after tax
    if tax(item, tax_rate) < 100:
        print(item)

90.02
89.99


We now know that the 90.02 and 89.99 items won't put us over our limit.

There isn't a technique and meta for this lesson because there is no new material . 

For practice, get the code running on your own, but change the prices and the cutoff. 